version: '3'

services:
  webapisample:
    image: webapisample
    read_only: true
    cap_drop:
      - ALL
    tmpfs:
      - /tmp
      - /var/run
    build:
      context: .
      dockerfile: WebApiSample/Dockerfile
